version: 2

project_name: hscli

before:
  hooks:
    - go mod download
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    main: ./main.go
    binary: hscli
    flags:
      - -trimpath
    ldflags:
      - -s -w -X github.com/obay/hscli/cmd.version={{.Version}}

archives:
  - id: versioned
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE
    format_overrides:
      - goos: windows
        formats: [zip]
  - id: versionless
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE
    format_overrides:
      - goos: windows
        formats: [zip]

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

release:
  github:
    owner: obay
    name: hscli
  mode: replace
  header: |
    ## What's Changed
  footer: |
    **Full Changelog**: https://github.com/obay/hscli/compare/{{ .PreviousTag }}...{{ .Tag }}

scoops:
  - ids:
      - versionless
    repository:
      owner: obay
      name: scoop-bucket
    homepage: "https://github.com/obay/hscli"
    description: "A CLI tool for managing HubSpot contacts"
    license: "MIT"
    skip_upload: false

homebrew_casks:
  - ids:
      - versionless
    repository:
      owner: obay
      name: homebrew-tap
    name: hscli
    homepage: "https://github.com/obay/hscli"
    description: "A CLI tool for managing HubSpot contacts"
    license: "MIT"
    url:
      verified: github.com/obay/hscli
    # If the binary isn't signed/notarized, unquarantine it so users don't get blocked
    hooks:
      post:
        install: |
          if OS.mac?
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/hscli"], sudo: false
          end

nfpms:
  - id: packages
    package_name: hscli
    file_name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    maintainer: "obay <your-email@example.com>"
    description: "A CLI tool for managing HubSpot contacts"
    homepage: "https://github.com/obay/hscli"
    license: "MIT"
    formats:
      - deb
      - rpm
    bindir: /usr/bin

