# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hsctl < Formula
  desc "A CLI tool for managing HubSpot contacts"
  homepage "https://github.com/obay/hsctl"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/obay/hsctl/releases/download/v0.1.0/hsctl_0.1.0_darwin_amd64.tar.gz"
      sha256 "PLACEHOLDER_SHA256"

      def install
        bin.install "hsctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/obay/hsctl/releases/download/v0.1.0/hsctl_0.1.0_darwin_arm64.tar.gz"
      sha256 "PLACEHOLDER_SHA256"

      def install
        bin.install "hsctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/obay/hsctl/releases/download/v0.1.0/hsctl_0.1.0_linux_amd64.tar.gz"
      sha256 "PLACEHOLDER_SHA256"

      def install
        bin.install "hsctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/obay/hsctl/releases/download/v0.1.0/hsctl_0.1.0_linux_arm64.tar.gz"
      sha256 "PLACEHOLDER_SHA256"

      def install
        bin.install "hsctl"
      end
    end
  end

  test do
    system "#{bin}/hsctl --version"
  end
end
